name: test
on:
   workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name:trial
    steps:
      - name: test
        run: |
            echo "Testing of Git action."
            echo "secret is ${{secrets.MY_PAT}}".
            echo "Job status is ${{ job.status}}."          
