name: test
on:
   workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
            echo "Testing of Git action."
            echo "Job status is ${{ job.status}}."          
